[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl", "musl", "bash"]
cmds = ["rustup default 1.75.0"]

[phases.install]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "cd backend && ./auth_api" 