version: '3.8'

services:
  auth-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - JWT_SALT=your-super-secret-salt-here-change-in-production
      - JWT_EXPIRATION_SECS=86400
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge 