services:
  auth-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - JWT_SALT=your-super-secret-salt-here-change-in-production
      - JWT_EXPIRATION_SECS=86400
      - HOST=0.0.0.0
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
    #   interval: 60s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 120s
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge 