[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl", "musl"]

[phases.install]
cmds = ["cargo build --release"]

[phases.build]
cmds = ["cp target/release/auth_api ./auth_api"]

[start]
cmd = "./auth_api" 